name: Build Standalone APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Setup Expo CLI
        run: npm install -g @expo/cli eas-cli

      - name: Generate Android project for standalone build
        run: npx expo prebuild --platform android --clean

      - name: Update Gradle wrapper to required version
        run: |
          cd android
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-all.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "networkTimeout=10000" >> gradle/wrapper/gradle-wrapper.properties
          echo "validateDistributionUrl=true" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Clean Gradle cache
        run: |
          echo "Cleaning Gradle cache..."
          ./gradlew clean --refresh-dependencies
        working-directory: android

      - name: Build standalone release APK
        run: |
          echo "Building standalone release APK..."
          # Add retry logic for handling temporary network issues
          max_attempts=3
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "Build attempt $attempt of $max_attempts"
            if ./gradlew assembleRelease --stacktrace; then
              echo "Build successful!"
              break
            else
              echo "Build failed on attempt $attempt"
              if [ $attempt -eq $max_attempts ]; then
                echo "All build attempts failed"
                exit 1
              fi
              echo "Waiting 30 seconds before retry..."
              sleep 30
              attempt=$((attempt + 1))
            fi
          done
        working-directory: android

      - name: Upload standalone APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: coloring-app-standalone-apk
          path: android/app/build/outputs/apk/release/*.apk